# Generated by Django 2.0.7 on 2018-07-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.CharField(default='Hey I am using CardsApp', max_length=200)),
                ('url', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
