# Generated by Django 2.0.6 on 2018-07-05 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20180705_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 6, 40, 33, 553269, tzinfo=utc), verbose_name='date published'),
        ),
    ]
