# Generated by Django 2.0.7 on 2018-07-11 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20180711_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='card',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 7, 3, 24, 597026, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
