# Generated by Django 2.0.7 on 2018-07-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20180717_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
