# Generated by Django 2.0.7 on 2018-07-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_carddetails_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='public',
            new_name='private',
        ),
    ]
