# Generated by Django 2.0.7 on 2018-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_auto_20180718_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='model_pic',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
