# Generated by Django 2.0.7 on 2018-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_carddetails_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='model_pic',
            field=models.ImageField(upload_to='image'),
        ),
    ]
