# Generated by Django 2.0.6 on 2018-07-05 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcount',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 6, 36, 45, 625488, tzinfo=utc), verbose_name='date published'),
        ),
    ]
