# Generated by Django 2.0.6 on 2018-07-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180705_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentcount',
            name='pub_date',
        ),
    ]
