# Generated by Django 2.0.7 on 2018-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_commentcount_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='commentcount',
            name='reply',
            field=models.ManyToManyField(default=1, to='comment.Reply'),
        ),
    ]
